In [15]:
#Importing libraries

import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression


import warnings 
warnings.filterwarnings('ignore')

In [16]:
df = pd.read_csv("d:/DAMI (Data Mining)/Week 05/CaoThiNgocPhung_21110276/train.csv")

In [17]:
df.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,1.5Fin,5,5,1993,1995,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,Wood,Gd,TA,No,GLQ,732,Unf,0,64,796,GasA,Ex,Y,SBrkr,796,566,0,1362,1,0,1,1,1,1,TA,5,Typ,0,NaN,Attchd,1993.0,Unf,2,480,TA,TA,Y,40,30,0,320,0,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,1Story,8,5,2004,2005,Gable,CompShg,VinylSd,VinylSd,Stone,186.0,Gd,TA,PConc,Ex,TA,Av,GLQ,1369,Unf,0,317,1686,GasA,Ex,Y,SBrkr,1694,0,0,1694,1,0,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2004.0,RFn,2,636,TA,TA,Y,255,57,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NWAmes,PosN,Norm,1Fam,2Story,7,6,1973,1973,Gable,CompShg,HdBoard,HdBoard,Stone,240.0,TA,TA,CBlock,Gd,TA,Mn,ALQ,859,BLQ,32,216,1107,GasA,Ex,Y,SBrkr,1107,983,0,2090,1,0,2,1,3,1,TA,7,Typ,2,TA,Attchd,1973.0,RFn,2,484,TA,TA,Y,235,204,228,0,0,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Artery,Norm,1Fam,1.5Fin,7,5,1931,1950,Gable,CompShg,BrkFace,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,TA,No,Unf,0,Unf,0,952,952,GasA,Gd,Y,FuseF,1022,752,0,1774,0,0,2,0,2,2,TA,8,Min1,2,TA,Detchd,1931.0,Unf,2,468,Fa,TA,Y,90,0,205,0,0,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,BrkSide,Artery,Artery,2fmCon,1.5Unf,5,6,1939,1950,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,BrkTil,TA,TA,No,GLQ,851,Unf,0,140,991,GasA,Ex,Y,SBrkr,1077,0,0,1077,1,0,1,0,2,2,TA,5,Typ,2,TA,Attchd,1939.0,RFn,1,205,Gd,TA,Y,0,4,0,0,0,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

Data Cleaning

In [34]:
df.isna().sum().sort_values(ascending = False).head(20)
missing_values = pd.DataFrame({'Total_NaN': df.isna().sum().sort_values(ascending = False).head(20)})
missing_values['NaN_Percent'] = missing_values['Total_NaN']/1460
missing_values

              Total_NaN  NaN_Percent
PoolQC             1453     0.995205
MiscFeature        1406     0.963014
Alley              1369     0.937671
Fence              1179     0.807534
MasVnrType          872     0.597260
FireplaceQu         690     0.472603
LotFrontage         259     0.177397
GarageYrBlt          81     0.055479
GarageCond           81     0.055479
GarageType           81     0.055479
GarageFinish         81     0.055479
GarageQual           81     0.055479
BsmtFinType2         38     0.026027
BsmtExposure         38     0.026027
BsmtQual             37     0.025342
BsmtCond             37     0.025342
BsmtFinType1         37     0.025342
MasVnrArea            8     0.005479
Electrical            1     0.000685
Id                    0     0.000000

In [41]:
for variable in missing_values.index:
    if missing_values.loc[variable]['NaN_Percent'] > 0.15:
        df = df.drop(labels = variable, axis = 1)

In [48]:
missing_values = pd.DataFrame({'Total_NaN': df.isna().sum().sort_values(ascending = False)})
missing_values['NaN_Percent'] = missing_values['Total_NaN']/1460
missing_values.head(14)

              Total_NaN  NaN_Percent
GarageType           81     0.055479
GarageCond           81     0.055479
GarageYrBlt          81     0.055479
GarageFinish         81     0.055479
GarageQual           81     0.055479
BsmtFinType2         38     0.026027
BsmtExposure         38     0.026027
BsmtFinType1         37     0.025342
BsmtCond             37     0.025342
BsmtQual             37     0.025342
MasVnrArea            8     0.005479
Electrical            1     0.000685
WoodDeckSF            0     0.000000
PavedDrive            0     0.000000

In [55]:
missing_values_df= df[list(missing_values.index)]
missing_values_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 74 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   GarageType     1379 non-null   object
 1   GarageCond     1379 non-null   object
 2   GarageYrBlt    1379 non-null   float64
 3   GarageFinish   1379 non-null   object
 4   GarageQual     1379 non-null   object
 5   BsmtFinType2   1422 non-null   object
 6   BsmtExposure   1422 non-null   object
 7   BsmtFinType1   1423 non-null   object
 8   BsmtCond       1423 non-null   object
 9   BsmtQual       1423 non-null   object
 10  MasVnrArea     1452 non-null   float64
 11  Electrical     1459 non-null   object
 12  WoodDeckSF     1460 non-null   int64
 13  PavedDrive     1460 non-null   object
 14  LowQualFinSF   1460 non-null   int64
 15  GrLivArea      1460 non-null   int64
 16  BsmtFullBath   1460 non-null   int64
 17  BsmtHalfBath   1460 non-null   int64
 18  FullBath       1460 non-null   int64
 19  HalfBath       1460 non-null   int64
 20  SaleCondition  1460 non-null   object
 21  BedroomAbvGr   1460 non-null   int64
 22  SaleType       1460 non-null   object
 23  YrSold         1460 non-null   int64
 24  MoSold         1460 non-null   int64
 25  MiscVal        1460 non-null   int64
 26  KitchenAbvGr   1460 non-null   int64
 27  KitchenQual    1460 non-null   object
 28  TotRmsAbvGrd   1460 non-null   int64
 29  PoolArea       1460 non-null   int64
 30  Functional     1460 non-null   object
 31  Fireplaces     1460 non-null   int64
 32  2ndFlrSF       1460 non-null   int64
 33  ScreenPorch    1460 non-null   int64
 34  3SsnPorch      1460 non-null   int64
 35  GarageCars     1460 non-null   int64
 36  GarageArea     1460 non-null   int64
 37  EnclosedPorch  1460 non-null   int64
 38  OpenPorchSF    1460 non-null   int64
 39  Id             1460 non-null   int64
 40  HeatingQC      1460 non-null   object
 41  1stFlrSF       1460 non-null   int64
 42  OverallCond    1460 non-null   int64
 43  MSZoning       1460 non-null   object
 44  LotArea        1460 non-null   int64
 45  Street         1460 non-null   object
 46  LotShape       1460 non-null   object
 47  LandContour    1460 non-null   object
 48  Utilities      1460 non-null   object
 49  LotConfig      1460 non-null   object
 50  LandSlope      1460 non-null   object
 51  Neighborhood   1460 non-null   object
 52  Condition1     1460 non-null   object
 53  Condition2     1460 non-null   object
 54  BldgType       1460 non-null   object
 55  HouseStyle     1460 non-null   object
 56  OverallQual    1460 non-null   int64
 57  YearBuilt      1460 non-null   int64
 58  CentralAir     1460 non-null   object
 59  YearRemodAdd   1460 non-null   int64
 60  RoofStyle      1460 non-null   object
 61  RoofMatl       1460 non-null   object
 62  Exterior1st    1460 non-null   object
 63  Exterior2nd    1460 non-null   object
 64  ExterQual      1460 non-null   object
 65  ExterCond      1460 non-null   object
 66  Foundation     1460 non-null   object
 67  BsmtFinSF1     1460 non-null   int64
 68  BsmtFinSF2     1460 non-null   int64
 69  BsmtUnfSF      1460 non-null   int64
 70  TotalBsmtSF    1460 non-null   int64
 71  Heating        1460 non-null   object
 72  MSSubClass     1460 non-null   int64
 73  SalePrice      1460 non-null   int64
dtypes: float64(2), int64(35), object(37)
memory usage: 844.2+ KB

In [62]:

#Garage Variables

    #GarageYrBlt:
index_with_null_values_GarageYrBlt = df[df['GarageYrBlt'].isna()][['GarageYrBlt']].index
for index in index_with_null_values_GarageYrBlt:
    df['GarageYrBlt'][index] = df['YearBuilt'][index]
df['GarageYrBlt'] = df['GarageYrBlt'].astype(int)
    #Garage các biến phân loại:
df[['GarageType', 'GarageCond', 'GarageFinish', 'GarageQual']] = df[['GarageType', 'GarageCond', 'GarageFinish', 'GarageQual']].fillna('None')


#Biến tầng hầm
df[['BsmtFinType2','BsmtFinType1','BsmtExposure','BsmtCond','BsmtQual']] = df[['BsmtFinType2','BsmtFinType1','BsmtExposure','BsmtCond','BsmtQual']].fillna('None')


#Miếng dán veneer biến đổi
df[['MasVnrArea']] = df[['MasVnrArea']].fillna(0)


#Biến điện
df[['Electrical']] = df[['Electrical']].fillna('Mix')

In [63]:
df.isna().sum().max()
rows, cols = df.shape
print(f'After cleaning the dataset, the dataframe has {cols} columns and {rows} rows')

After cleaning the dataset, the dataframe has 74 columns and 1460 rows

Data Analysis

In [64]:
categorical_variables = df.select_dtypes(include='object').columns
categorical_variables

Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional',
       'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
       'SaleType', 'SaleCondition'],
      dtype='object')

Regression

In [65]:
#Nhận hình nộm cho các biến phân loại
df_dummies = pd.get_dummies(df, columns = categorical_variables, drop_first = True)
df_dummies=df_dummies.drop(labels = 'Id', axis=1)
df_dummies.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Pave,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_HLS,LandContour_Low,LandContour_Lvl,Utilities_NoSeWa,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,LandSlope_Mod,LandSlope_Sev,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,Neighborhood_Edwards,Neighborhood_Gilbert,Neighborhood_IDOTRR,Neighborhood_MeadowV,Neighborhood_Mitchel,Neighborhood_NAmes,Neighborhood_NPkVill,Neighborhood_NWAmes,Neighborhood_NoRidge,Neighborhood_NridgHt,Neighborhood_OldTown,Neighborhood_SWISU,Neighborhood_Sawyer,Neighborhood_SawyerW,Neighborhood_Somerst,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,Condition1_Feedr,Condition1_Norm,Condition1_PosA,Condition1_PosN,Condition1_RRAe,Condition1_RRAn,Condition1_RRNe,Condition1_RRNn,Condition2_Feedr,Condition2_Norm,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,RoofMatl_CompShg,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,Exterior1st_AsphShn,Exterior1st_BrkComm,Exterior1st_BrkFace,Exterior1st_CBlock,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing,Exterior2nd_AsphShn,Exterior2nd_Brk Cmn,Exterior2nd_BrkFace,Exterior2nd_CBlock,Exterior2nd_CmentBd,Exterior2nd_HdBoard,Exterior2nd_ImStucc,Exterior2nd_MetalSd,Exterior2nd_Other,Exterior2nd_Plywood,Exterior2nd_Stone,Exterior2nd_Stucco,Exterior2nd_VinylSd,Exterior2nd_Wd Sdng,Exterior2nd_Wd Shng,ExterQual_Fa,ExterQual_Gd,ExterQual_TA,ExterCond_Fa,ExterCond_Gd,ExterCond_Po,ExterCond_TA,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,BsmtQual_Fa,BsmtQual_Gd,BsmtQual_None,BsmtQual_TA,BsmtCond_Gd,BsmtCond_None,BsmtCond_Po,BsmtCond_TA,BsmtExposure_Gd,BsmtExposure_Mn,BsmtExposure_No,BsmtExposure_None,BsmtFinType1_BLQ,BsmtFinType1_GLQ,BsmtFinType1_LwQ,BsmtFinType1_None,BsmtFinType1_Rec,BsmtFinType1_Unf,BsmtFinType2_BLQ,BsmtFinType2_GLQ,BsmtFinType2_LwQ,BsmtFinType2_None,BsmtFinType2_Rec,BsmtFinType2_Unf,Heating_GasA,Heating_GasW,Heating_Grav,Heating_OthW,Heating_Wall,HeatingQC_Fa,HeatingQC_Gd,HeatingQC_Po,HeatingQC_TA,CentralAir_Y,Electrical_FuseF,Electrical_FuseP,Electrical_Mix,Electrical_SBrkr,KitchenQual_Fa,KitchenQual_Gd,KitchenQual_TA,Functional_Maj2,Functional_Min1,Functional_Min2,Functional_Mod,Functional_Sev,Functional_Typ,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageType_None,GarageFinish_None,GarageFinish_RFn,GarageFinish_Unf,GarageQual_Fa,GarageQual_Gd,GarageQual_None,GarageQual_Po,GarageQual_TA,GarageCond_Fa,GarageCond_Gd,GarageCond_None,GarageCond_Po,GarageCond_TA,PavedDrive_P,PavedDrive_Y,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,8450,7,5,2003,2003,196.0,706,0,150,856,856,854,0,1710,1,0,2,1,3,1,8,0,2003,2,548,0,61,0,0,0,0,0,2,2008,208500,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False
1,20,9600,6,8,1976,1976,0.0,978,0,284,1262,1262,0,0,1262,0,1,2,0,3,1,6,1,1976,2,460,298,0,0,0,0,0,0,5,2007,181500,False,False,True,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,False,False,True,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False
2,60,11250,7,5,2001,2002,162.0,486,0,434,920,920,866,0,1786,1,0,2,1,3,1,6,1,2001,2,608,0,42,0,0,0,0,0,9,2008,223500,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False
3,70,9550,7,5,1915,1970,0.0,216,0,540,756,961,756,0,1717,1,0,1,0,3,1,7,1,1998,3,642,0,35,272,0,0,0,0,2,2006,140000,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,True,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False
4,60,14260,8,5,2000,2000,350.0,655,0,490,1145,1145,1053,0,2198,1,0,2,1,4,1,9,1,2000,3,836,192,84,0,0,0,0,0,12,2008,250000,False,False,True,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False

In [66]:
from sklearn.model_selection import train_test_split

X = df_dummies.drop(columns='SalePrice')
y = df_dummies['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size   = 0.2,
                                                    random_state = 1234,
                                                    shuffle      = True)

In [67]:
print(f'The shape of X_train is {X_train.shape}')
print(f'The shape of X_test is {X_test.shape}')
print(f'The shape of y_train is {y_train.shape}')
print(f'The shape of y_test is {y_test.shape}')

The shape of X_train is (1168, 237)
The shape of X_test is (292, 237)
The shape of y_train is (1168,)
The shape of y_test is (292,)

In [68]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train) #StandardScaler.fit_transform() chuẩn hóa dữ liệu, đảm bảo rằng chúng có giá trị trung bình bằng 0 và độ lệch chuẩn bằng 1.
X_test_scaled = scaler.transform(X_test)       #StandardScaler.transform() áp dụng phép chuyển đổi dựa trên số liệu thống kê được tính toán trước đó trong fit_transform

#Để có được một df với các cột tên, hãy làm như sau:
X_train_scaled_df = pd.DataFrame(X_train_scaled) #Chúng tôi nhận được một df không có cột tên
X_train_scaled_df.columns = list(df_dummies.columns.drop('SalePrice')) #Chúng tôi thêm tên cột

In [69]:
model = LinearRegression()
model.fit(X_train_scaled_df, y_train)

LinearRegression()

In [71]:
#Kiểm tra dự đoán
pred = model.predict(X_train_scaled_df)
pred = pred.flatten()
pred[:10]

array([284751.9962069 , 167059.71148974, 108783.1368319 , 104699.6099136 ,
       118108.95337928, 280822.90636315, 251886.73448815, 109272.0743319 ,
       137565.53917565,  88166.95479194])

In [72]:
# Lỗi từ mô hình
rmse_ols = mean_squared_error(
            y_true  = y_train,
            y_pred  = pred,
            squared = False
           )
print("")
print(f"The error(rmse) is: {rmse_ols}")

The error(rmse) is: 20797.104893788128

In [73]:
r2_ols = model.score(X_train_scaled_df,y_train)
r2_ols
print(f"The R^2 is: {r2_ols}")

The R^2 is: 0.9335453403619332

In [74]:
# Tính MSE
mse_ols = mean_squared_error(y_true  = y_train,  # Giá trị thực
                             y_pred  = pred,      # Giá trị dự đoán
                             squared = True       # squared=True để tính MSE thay vì RMSE
                            )   
print("")
print(f"The error (MSE) is: {mse_ols}")

The error (MSE) is: 432519571.9632261